project:
  type: book

book:
  title: "Statistical inference on used car data using linear regression in R"
  author: "Linus Rundberg Streuli"
  date: "4/10/2024"
  favicon: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - theory.qmd
    - method.qmd
    - results.qmd
    - conclusions.qmd
    - summary.qmd
    - appendix_a.qmd
    - appendix_b.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl
number-sections: true
number-depth: 2
tbl-cap-location: bottom
# bibliographystyle: apalike

warning: false

format:
  html:
    theme: cosmo
  pdf:
    papersize: A4
    header-includes: |
      \titlehead{\centering\includegraphics[width=6in]{cover.png}}



